/*
 * tn.h - token type
 * programmer - ±èÁöÇö, ±èÇÏ¿¬, Á¤Çý¹Î
 * date -
 */


enum tokentypes {
	TEOF,
	TPLUS, TMINUS, TSTAR, TSLASH, TMOD,
	TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
	TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE,
	TNOT, TAND, TOR, TINC, TDEC,
	TLPARE, TRPARE, TLCURLY, TRCURLY, TLSQUARE, TRSQUARE, TSEMI, TCOMMA,
	TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE,
	TIDENT, TREMARK,
	TFLOAT, TINTEGER
};